export const MCP_PRESETS = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    category: 'Files & Storage',
    description: 'Read, write, search, and manage local files and directories',
    icon: '📁',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-filesystem <ALLOWED_PATH>',
    envTemplate: [],
    note: 'Replace <ALLOWED_PATH> with the directory to expose, e.g. /Users/you/projects',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    category: 'Files & Storage',
    description: 'Query and manage a local SQLite database file',
    icon: '🗄️',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-sqlite <DB_PATH>',
    envTemplate: [],
    note: 'Replace <DB_PATH> with the path to your .db file',
  },
  {
    id: 'git',
    name: 'Git',
    category: 'Dev Tools',
    description: 'Git operations: log, diff, commit, branch management',
    icon: '🌿',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-git --repository <REPO_PATH>',
    envTemplate: [],
    note: 'Replace <REPO_PATH> with the path to your git repository',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Dev Tools',
    description: 'Search repos, manage issues, PRs, and files via GitHub API',
    icon: '🐙',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-github',
    envTemplate: [
      { key: 'GITHUB_PERSONAL_ACCESS_TOKEN', secret: true, description: 'Personal access token (repo scope) — create at github.com/settings/tokens' },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Dev Tools',
    description: 'Manage GitLab projects, issues, and merge requests',
    icon: '🦊',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-gitlab',
    envTemplate: [
      { key: 'GITLAB_PERSONAL_ACCESS_TOKEN', secret: true, description: 'Personal access token with api scope' },
      { key: 'GITLAB_API_URL', value: 'https://gitlab.com/api/v4', secret: false, description: 'API base URL — change for self-hosted instances' },
    ],
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    category: 'Databases',
    description: 'Query PostgreSQL databases with full SQL support',
    icon: '🐘',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-postgres postgresql://user:password@localhost:5432/database',
    envTemplate: [],
    note: 'Replace the connection string in Args with your actual credentials',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    category: 'Web & Search',
    description: 'Real-time web and news search via the Brave Search API',
    icon: '🦁',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-brave-search',
    envTemplate: [
      { key: 'BRAVE_API_KEY', secret: true, description: 'Brave Search API key — get one at brave.com/search/api' },
    ],
  },
  {
    id: 'duckduckgo-search',
    name: 'DuckDuckGo Search',
    category: 'Web & Search',
    description: 'Free web search through DuckDuckGo with no API key',
    icon: '🦆',
    transport: 'stdio',
    command: 'npx',
    args: '-y duckduckgo-mcp-server',
    envTemplate: [],
    note: 'Community MCP server. It exposes a DuckDuckGo web search tool and uses built-in rate limits.',
  },
  {
    id: 'fetch',
    name: 'Fetch / HTTP',
    category: 'Web & Search',
    description: 'Make HTTP requests and fetch web content or API data',
    icon: '🌐',
    transport: 'stdio',
    command: 'uvx',
    args: 'mcp-server-fetch',
    envTemplate: [],
    note: 'Fetch is distributed as a Python MCP server. This preset requires uvx.',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    category: 'Web & Search',
    description: 'Browser automation — take screenshots, fill forms, click elements',
    icon: '🤖',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-puppeteer',
    envTemplate: [],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Productivity',
    description: 'Read and post Slack messages, manage channels and threads',
    icon: '💬',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-slack',
    envTemplate: [
      { key: 'SLACK_BOT_TOKEN', secret: true, description: 'Bot User OAuth Token (xoxb-...) — create at api.slack.com/apps' },
      { key: 'SLACK_TEAM_ID', secret: false, description: 'Workspace Team ID, e.g. T01ABC123' },
    ],
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'Productivity',
    description: 'Read and search files stored in Google Drive',
    icon: '📂',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-gdrive',
    envTemplate: [],
    note: 'Requires Google OAuth setup — see @modelcontextprotocol/server-gdrive README',
  },
  {
    id: 'memory',
    name: 'Memory',
    category: 'AI & Reasoning',
    description: 'Persistent knowledge graph memory that survives across sessions',
    icon: '🧠',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-memory',
    envTemplate: [],
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    category: 'AI & Reasoning',
    description: 'Structured step-by-step reasoning for complex multi-part problems',
    icon: '🔢',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-sequential-thinking',
    envTemplate: [],
  },
  {
    id: 'everart',
    name: 'EverArt',
    category: 'AI & Reasoning',
    description: 'AI image generation via the EverArt API',
    icon: '🎨',
    transport: 'stdio',
    command: 'npx',
    args: '-y @modelcontextprotocol/server-everart',
    envTemplate: [
      { key: 'EVERART_API_KEY', secret: true, description: 'EverArt API key — get one at everart.ai' },
    ],
  },
];

export const PRESET_CATEGORIES = [...new Set(MCP_PRESETS.map(p => p.category))];
