const { defineRecipe } = require('./recipeFactory');

const ENGINEERING_RECIPES = [
  // ══ Engineering ══════════════════════════════════════════════════════════════
  defineRecipe({
    id: 'code_review',
    name: 'Code Review Crew',
    category: 'Engineering',
    summary: 'Structured multi-lens code review: scope, implementation, tests, security, and a synthesized verdict',
    placeholder: 'Point the crew at the change to review...\ne.g. Review the pending changes on the current branch for correctness, test coverage, and security',
    strict: true,
    executionPolicy: { mode: 'read_only', github_review: true, github_publish: false },
    roles: [
      {
        key: 'review_lead', title: 'Review Lead', agent: 'Dana Whitfield',
        caps: ['coding'], repo: 'read',
        mission: 'to scope the review so every reviewer knows exactly what changed and what matters.',
        duties: [
          'Read project_context first. If it includes review_target/changed_files, treat that PR metadata as authoritative and do not invent another diff range.',
          'Read the diff/changed files in the repository workspace with status awareness and inventory what actually changed.',
          'Do not read deleted/removed files from the head working tree. For status D/removed entries, inspect the diff or base revision and mark them as deletions.',
          'Classify the change (feature, fix, refactor, config) and flag the riskiest areas for deeper review.',
          'List the files each downstream reviewer must read and the questions they must answer.',
          'Do NOT review the code yourself — you set the scope; the specialists judge it.',
        ],
        handoff: 'Review scope handoff',
        handoffContents: 'the file inventory, change classification, risk areas, and per-reviewer focus questions',
      },
      {
        key: 'implementation_reviewer', title: 'Implementation Reviewer', agent: 'Marcus Vale',
        caps: ['coding'], repo: 'read',
        mission: 'to judge whether the implementation is correct, idiomatic, and maintainable.',
        duties: [
          'Read every file in the review scope; trace the logic rather than skimming names.',
          'Hunt for correctness bugs: broken edge cases, bad state handling, races, and API misuse.',
          'Check the change matches the surrounding architecture and code conventions.',
          'Cite file:line for every finding and rate each finding by severity.',
        ],
        handoff: 'Implementation review handoff',
        handoffContents: 'correctness findings with file:line citations and severities, plus what you verified clean',
      },
      {
        key: 'test_reviewer', title: 'Test Reviewer', agent: 'Elif Kaya',
        caps: ['coding'], repo: 'read', network: 'bridge',
        mission: 'to verify the change is actually tested — by running the tests, not reading them.',
        duties: [
          'RUN the relevant test suite with shell and paste the real output; a PASS claim without output is a defect.',
          'The reviewed repository is mounted read-only. NEVER run npm install, npm audit fix, formatters, generators, or any command that changes source files or lockfiles. If dependencies are unavailable, report that verification gap instead of installing them.',
          'Map each behavior the change introduces to a test that exercises it; list untested behaviors.',
          'Check tests assert outcomes, not implementation details, and would fail if the change regressed.',
        ],
        handoff: 'Test review handoff',
        handoffContents: 'executed test results, the coverage map, untested behaviors, and flaky/missing tests',
      },
      {
        key: 'security_reviewer', title: 'Security Reviewer', agent: 'Yusuf Rahman',
        caps: ['coding'], repo: 'read', github: true,
        mission: 'to find what the change exposes: injection, authz gaps, secrets, and unsafe dependencies.',
        duties: [
          'Review the changed code for injection, path traversal, SSRF, authz/authn gaps, and unsafe deserialization.',
          'Check for secrets, tokens, or credentials introduced in code or config.',
          'Read open security alerts with github_security_alerts when a token is available; report clearly if it is not.',
          'Rate each finding by severity and say explicitly when you found nothing in an area you checked.',
        ],
        handoff: 'Security review handoff',
        handoffContents: 'security findings with severity and file:line citations, plus the areas verified clean',
      },
      {
        key: 'review_synthesizer', title: 'Review Synthesizer', agent: 'Priya Nand',
        caps: ['writing', 'analysis'], repo: null, files: true,
        artifact: 'the full review report as a Colony run artifact named <change>-review.md',
        mission: 'to merge every reviewer’s findings into one actionable verdict.',
        duties: [
          'Consolidate all upstream findings, dedupe overlaps, and resolve conflicting judgments explicitly.',
          'Order findings by severity with the evidence each reviewer cited.',
          'Give a clear verdict: approve, approve-with-nits, or request-changes — and what must change to pass.',
          'A clean review is a valid result. When no changes are required, say so explicitly and still save the report with save_artifact.',
        ],
        handoff: 'Final review verdict',
        handoffContents: 'the verdict, the ordered findings list, and the review report file path',
      },
    ],
  }),

  defineRecipe({
    id: 'incident_response',
    name: 'Incident Response Team',
    category: 'Engineering',
    summary: 'Staged incident handling: command, evidence, root cause, fix, verification, and comms',
    placeholder: 'Describe the incident: what broke, when it started, and what you observe...\ne.g. API latency spiked 10x after last night’s deploy; error rate climbing',
    strict: true,
    executionPolicy: { mode: 'repository_write', github_review: false, github_publish: true },
    roles: [
      {
        key: 'incident_commander', title: 'Incident Commander', agent: 'Rosa Delgado',
        caps: ['analysis'], repo: 'read', sandbox: true,
        mission: 'to size up the incident and direct the response so nobody guesses in parallel.',
        duties: [
          'Establish severity, blast radius, user impact, and what is definitely NOT affected.',
          'Write the incident timeline as facts arrive; separate confirmed facts from hypotheses.',
          'Define what evidence the collector must gather first and what mitigation is acceptable meanwhile.',
        ],
        handoff: 'Incident command handoff',
        handoffContents: 'severity assessment, impact statement, current timeline, and the evidence collection priorities',
      },
      {
        key: 'evidence_collector', title: 'Evidence Collector', agent: 'Tom Okafor',
        caps: ['coding'], repo: 'read',
        mission: 'to gather the raw facts — logs, diffs, configs, timings — before anyone theorizes.',
        duties: [
          'Inspect the repository workspace: recent commits/diffs, config changes, and anything matching the incident window.',
          'Run read-only shell commands to collect evidence; paste actual output, never summaries of imagined output.',
          'Timestamp every piece of evidence and note what you looked for but could not access.',
        ],
        handoff: 'Evidence handoff',
        handoffContents: 'the evidence inventory with timestamps and command output, plus access gaps',
      },
      {
        key: 'root_cause_analyst', title: 'Root Cause Analyst', agent: 'Ingrid Solberg',
        caps: ['coding'], repo: 'read',
        mission: 'to converge on the actual root cause with evidence, not the first plausible story.',
        duties: [
          'Build competing hypotheses from the evidence and test each against the timeline.',
          'Trace the failing path in the code; cite file:line for the defect you conclude is causal.',
          'State the confidence level and what single piece of missing evidence would change your conclusion.',
        ],
        handoff: 'Root cause handoff',
        handoffContents: 'the root cause with code citations, rejected hypotheses and why, and the proposed fix direction',
      },
      {
        key: 'fix_engineer', title: 'Fix Engineer', agent: 'Andre Boateng',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to implement the smallest correct fix for the identified root cause.',
        duties: [
          'MAKE REAL CHANGES: edit the actual files with your sandbox tools; prose is not a fix.',
          'Fix the root cause, not the symptom; keep the change minimal and scoped to the incident.',
          'VERIFY BY EXECUTING: run the build/tests that prove the fix and paste the output.',
        ],
        handoff: 'Fix handoff',
        handoffContents: 'changed file paths, the fix rationale, and verification command output',
      },
      {
        key: 'verification_lead', title: 'Verification Lead', agent: 'Mei-Ling Zhou',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to independently prove the fix resolves the incident without regressing anything.',
        duties: [
          'Re-run the failing scenario and the surrounding test suite yourself; do not trust the fix engineer’s output.',
          'Check for regressions in adjacent behavior and confirm the incident symptoms are gone.',
          'Report PASS/FAIL per check with the actual command output as evidence.',
        ],
        handoff: 'Verification handoff',
        handoffContents: 'PASS/FAIL results with output, regression checks performed, and residual risk',
      },
      {
        key: 'comms_scribe', title: 'Comms Scribe', agent: 'Fatima Haddad',
        caps: ['writing'], repo: 'write', files: true,
        artifact: 'the postmortem to docs/incidents/<date>-postmortem.md',
        mission: 'to turn the incident into a blameless postmortem and clear stakeholder comms.',
        duties: [
          'Write the postmortem: timeline, impact, root cause, fix, verification, and prevention actions.',
          'Draft a short stakeholder-facing summary in plain language (no internal jargon).',
          'List concrete follow-up actions with suggested owners.',
        ],
        handoff: 'Final incident report',
        handoffContents: 'the postmortem file path, the stakeholder summary, and the follow-up action list',
      },
    ],
  }),

  defineRecipe({
    id: 'docs_release',
    name: 'Docs Release Crew',
    category: 'Engineering',
    summary: 'Documentation delivery chain: plan, write, curate the changelog, edit, and publish',
    placeholder: 'Describe the documentation to produce or update...\ne.g. Document the new webhooks API and update the changelog for v2.3',
    strict: true,
    executionPolicy: { mode: 'repository_write', github_review: false, github_publish: true },
    roles: [
      {
        key: 'documentation_planner', title: 'Documentation Planner', agent: 'Nora Lindqvist',
        caps: ['analysis', 'writing'], repo: 'read', sandbox: true,
        mission: 'to map what documentation is needed, for whom, and where it lives.',
        duties: [
          'Audit the existing docs in the repository and identify gaps against the requested scope.',
          'Define the audience, the doc types needed (guide, reference, changelog), and the target file paths.',
          'Produce an ordered outline per document with the source files/features each section must cover.',
        ],
        handoff: 'Docs plan handoff',
        handoffContents: 'the documentation plan: target paths, outlines, audiences, and source references',
      },
      {
        key: 'technical_writer', title: 'Technical Writer', agent: 'Gabriel Mensah',
        caps: ['writing'], repo: 'write', files: true, sandbox: true,
        artifact: 'each planned document to its target path in the repo',
        mission: 'to write accurate, example-driven documentation that matches the actual code.',
        duties: [
          'Write each planned document to its target path; verify code examples against the real source, not memory.',
          'Match the repository’s existing doc voice, formatting, and structure.',
          'Flag any behavior you could not verify in code as an open question rather than documenting a guess.',
        ],
        handoff: 'Writing handoff',
        handoffContents: 'the written file paths, verified examples, and unverified claims needing review',
      },
      {
        key: 'changelog_curator', title: 'Changelog Curator', agent: 'Sofia Petrov',
        caps: ['writing'], repo: 'write', files: true, github: true,
        artifact: 'the updated CHANGELOG.md entry',
        mission: 'to curate an accurate, user-facing changelog for this release.',
        duties: [
          'Gather what actually shipped from the repo history and linked issues/PRs (github tools when available).',
          'Write user-facing changelog entries grouped by added/changed/fixed — describe impact, not commit messages.',
          'Keep versioning and date conventions consistent with the existing changelog.',
        ],
        handoff: 'Changelog handoff',
        handoffContents: 'the changelog entry, the shipped-changes inventory, and anything excluded and why',
      },
      {
        key: 'qa_editor', title: 'QA Editor', agent: 'Hana Suzuki',
        caps: ['writing', 'analysis'], repo: 'write', sandbox: true,
        mission: 'to edit every produced document for accuracy, clarity, and consistency.',
        duties: [
          'Check every claim and example against the actual code; run examples where possible.',
          'Fix unclear phrasing, broken links, and formatting inconsistencies directly in the files.',
          'Verify the docs match the plan’s outline and audience; report deviations.',
        ],
        handoff: 'Edit handoff',
        handoffContents: 'the edited file list, corrections made, and unresolved accuracy concerns',
      },
      {
        key: 'publisher', title: 'Publisher', agent: 'Owen Gallagher',
        caps: ['coding'], repo: 'write', network: 'bridge', github: true,
        mission: 'to run the final publish checks and stage the docs for release.',
        duties: [
          'Run the repo’s docs build/lint (if one exists) and paste the output; fix mechanical failures.',
          'Confirm every planned document exists at its target path with the edits applied.',
          'Summarize exactly what is ready to ship and any step that still needs a human.',
        ],
        handoff: 'Final publish report',
        handoffContents: 'the build/check output, the shipped file inventory, and remaining manual steps',
      },
    ],
  }),

  defineRecipe({
    id: 'security_review',
    name: 'Security Review Team',
    category: 'Engineering',
    summary: 'Security assessment chain: threat model, appsec review, dependency audit, remediation, and signoff',
    placeholder: 'Describe the scope to assess...\ne.g. Security-review the authentication and file-upload paths before the beta launch',
    strict: true,
    executionPolicy: { mode: 'repository_write', github_review: false, github_publish: true },
    roles: [
      {
        key: 'threat_modeler', title: 'Threat Modeler', agent: 'Leila Nasser',
        caps: ['analysis'], repo: 'read', sandbox: true,
        mission: 'to map the attack surface before anyone reads a line of code in detail.',
        duties: [
          'Identify entry points, trust boundaries, data flows, and assets from the actual repository layout.',
          'Enumerate threats per boundary (STRIDE-style) ranked by likelihood and impact.',
          'Define the specific questions the AppSec reviewer and dependency auditor must answer.',
        ],
        handoff: 'Threat model handoff',
        handoffContents: 'the attack surface map, ranked threats, and the focus questions for downstream reviewers',
      },
      {
        key: 'appsec_reviewer', title: 'AppSec Reviewer', agent: 'Viktor Almeida',
        caps: ['coding'], repo: 'read',
        mission: 'to review the code against the threat model and find real, exploitable weaknesses.',
        duties: [
          'Trace each ranked threat through the code; confirm or refute it with file:line evidence.',
          'Check input validation, authn/authz enforcement, secret handling, and unsafe patterns.',
          'Rate findings by severity with a concrete exploit scenario for each confirmed issue.',
        ],
        handoff: 'AppSec handoff',
        handoffContents: 'confirmed findings with severity, exploit scenarios, and code citations; threats refuted with evidence',
      },
      {
        key: 'dependency_auditor', title: 'Dependency Auditor', agent: 'Chidi Eze',
        caps: ['coding'], repo: 'read', network: 'bridge', github: true,
        mission: 'to audit the dependency tree for known vulnerabilities and risky packages.',
        duties: [
          'Run the ecosystem audit (e.g. "npm audit") and read open Dependabot/code-scanning alerts when available; paste real output.',
          'NEVER run "npm audit fix --force" or downgrade packages — report findings for deliberate remediation instead.',
          'Flag unmaintained or suspiciously new dependencies in the critical path.',
        ],
        handoff: 'Dependency audit handoff',
        handoffContents: 'the audit output, vulnerable packages with severities, and the recommended remediation order',
      },
      {
        key: 'remediation_engineer', title: 'Remediation Engineer', agent: 'Astrid Berg',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to fix the confirmed critical and high findings with real code changes.',
        duties: [
          'Fix findings in severity order with minimal, targeted changes; cite each fixed finding.',
          'VERIFY BY EXECUTING: re-run the audit/tests that prove each fix and paste the output.',
          'Document any finding deliberately deferred, with the risk acceptance rationale.',
        ],
        handoff: 'Remediation handoff',
        handoffContents: 'fixed findings with changed file paths and verification output, plus deferred items with rationale',
      },
      {
        key: 'security_signoff', title: 'Security Signoff', agent: 'Ruth Okonkwo',
        caps: ['analysis', 'writing'], repo: 'read', files: true, github: true,
        artifact: 'the assessment report to docs/security/<scope>-assessment.md',
        mission: 'to render the final security verdict on the assessed scope.',
        duties: [
          'Verify every critical/high finding is fixed or explicitly risk-accepted; do NOT sign off otherwise.',
          'Write the assessment report: scope, threats, findings, remediations, and residual risk.',
          'Give a clear verdict: pass, pass-with-conditions, or fail — with the conditions listed.',
        ],
        handoff: 'Final security verdict',
        handoffContents: 'the verdict, residual risk summary, and the assessment report file path',
      },
    ],
  }),

  defineRecipe({
    id: 'refactor_migration',
    name: 'Refactor & Migration Crew',
    category: 'Engineering',
    summary: 'Staged refactor/migration: architecture, plan, implementation, regression QA, and release coordination',
    placeholder: 'Describe the refactor or migration...\ne.g. Migrate the API layer from Express callbacks to async handlers without behavior changes',
    strict: true,
    executionPolicy: { mode: 'repository_write', github_review: false, github_publish: true },
    roles: [
      {
        key: 'architect', title: 'Architect', agent: 'Isabel Fontaine',
        caps: ['coding'], repo: 'read',
        mission: 'to define the target architecture and the invariants the migration must preserve.',
        duties: [
          'Read the current structure in the repository; map what exists before prescribing what should.',
          'Define the target state, the invariants that must not break, and the seams to migrate along.',
          'Call out the riskiest coupling points and how to verify behavior is preserved.',
        ],
        handoff: 'Architecture handoff',
        handoffContents: 'the current-state map, target architecture, invariants, and risk points',
      },
      {
        key: 'migration_planner', title: 'Migration Planner', agent: 'Dmitri Volkov',
        caps: ['analysis', 'writing'], repo: 'write', files: true,
        artifact: 'the migration plan to docs/migrations/<name>-plan.md',
        mission: 'to slice the migration into safe, independently verifiable steps.',
        duties: [
          'Break the migration into ordered steps that each leave the codebase working.',
          'Define the verification command(s) for every step — what proves the step landed safely.',
          'Sequence steps to front-load risk discovery and keep any rollback simple.',
        ],
        handoff: 'Migration plan handoff',
        handoffContents: 'the ordered step plan with per-step verification, and the plan file path',
      },
      {
        key: 'refactor_engineer', title: 'Refactor Engineer', agent: 'Kwame Asante',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to execute the migration steps with real, verified code changes.',
        duties: [
          'Execute the plan step by step; MAKE REAL CHANGES with your sandbox tools.',
          'Run the step’s verification command after each step and paste the output before moving on.',
          'Stop and report — do not improvise — if a step reveals the plan’s assumptions were wrong.',
        ],
        handoff: 'Refactor handoff',
        handoffContents: 'completed steps with changed files and verification output, and any plan deviations',
      },
      {
        key: 'regression_qa', title: 'Regression QA', agent: 'Yuki Tanaka',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to prove behavior is unchanged where it must be, with executed evidence.',
        duties: [
          'Run the full test suite and the architect’s invariant checks; paste actual output.',
          'Probe the riskiest coupling points beyond the automated tests.',
          'Report PASS/FAIL per invariant; a regression found now is a success, not a failure.',
        ],
        handoff: 'Regression QA handoff',
        handoffContents: 'per-invariant PASS/FAIL with output, regressions found, and untested areas',
      },
      {
        key: 'release_coordinator', title: 'Release Coordinator', agent: 'Amara Diallo',
        caps: ['writing', 'record_keeping'], repo: 'write', files: true, github: true,
        artifact: 'the release notes / migration summary in the repo (CHANGELOG.md or docs/)',
        mission: 'to package the migration for release: notes, follow-ups, and the go/no-go call.',
        duties: [
          'Write the release notes: what changed, what to watch, and any operator action required.',
          'File follow-up work uncovered during the migration as explicit next steps (github issues when available).',
          'Give a go/no-go recommendation grounded in the QA evidence.',
        ],
        handoff: 'Final release report',
        handoffContents: 'the go/no-go recommendation, release notes path, and follow-up list',
      },
    ],
  }),

  // ══ Research ═════════════════════════════════════════════════════════════════
  defineRecipe({
    id: 'data_analysis',
    name: 'Data Analysis Crew',
    category: 'Research',
    summary: 'Data crew that profiles, prepares, models, visualizes, and synthesizes insight from real data',
    placeholder: 'Describe the dataset and the questions to answer...\ne.g. Analyze signups.csv for conversion drivers and seasonal patterns',
    roles: [
      {
        key: 'data_analyst', title: 'Data Analyst', agent: 'Carmen Reyes',
        caps: ['coding'], repo: 'read', network: 'bridge',
        mission: 'to profile the data and answer the mission’s questions with executed analysis.',
        duties: [
          'Load and profile the actual data with run_python; paste real output — never invent numbers.',
          'Answer each mission question with computed evidence; show the code that produced every figure.',
          'Report data quality issues (nulls, duplicates, outliers) that could bias conclusions.',
        ],
        handoff: 'Analysis handoff',
        handoffContents: 'the computed answers with supporting output, and data quality caveats',
      },
      {
        key: 'data_engineer', title: 'Data Engineer', agent: 'Lukas Meyer',
        caps: ['coding'], repo: 'write', network: 'bridge',
        mission: 'to make the data usable: cleaning, joining, and reproducible preparation scripts.',
        duties: [
          'Write reproducible preparation scripts (not one-off shell history) and run them to produce the clean dataset.',
          'Document every transformation and dropped record class so the analysis is auditable.',
          'Keep raw data untouched; derived data goes to separate files.',
        ],
        handoff: 'Data prep handoff',
        handoffContents: 'the prep script paths, the derived dataset locations, and the transformation log',
      },
      {
        key: 'statistician', title: 'Statistician', agent: 'Aisha Kamara',
        caps: ['coding'], network: 'bridge',
        mission: 'to test whether the observed patterns are real or noise.',
        duties: [
          'Choose tests appropriate to the data shape and state their assumptions explicitly.',
          'Run the tests with run_python and report effect sizes and uncertainty, not just p-values.',
          'Call out underpowered comparisons and multiple-testing risks honestly.',
        ],
        handoff: 'Statistics handoff',
        handoffContents: 'test results with effect sizes and confidence, assumption checks, and validity caveats',
      },
      {
        key: 'visualization_designer', title: 'Visualization Designer', agent: 'Theo Marchetti',
        caps: ['coding', 'design'], network: 'bridge',
        artifact: 'chart files (PNG/SVG) saved to the workspace',
        mission: 'to turn the confirmed findings into honest, readable charts.',
        duties: [
          'Generate the charts with run_python and save them as files; list every produced path.',
          'Choose chart forms that match the data relationship; never truncate axes to exaggerate.',
          'Annotate each chart with the finding it demonstrates.',
        ],
        handoff: 'Visualization handoff',
        handoffContents: 'the chart file paths and the finding each chart demonstrates',
      },
      {
        key: 'insight_synthesizer', title: 'Insight Synthesizer', agent: 'Grace Whitmore',
        caps: ['writing'], files: true,
        artifact: 'the final insights report saved to the workspace',
        mission: 'to synthesize the analysis into decisions someone can act on.',
        duties: [
          'Lead with the answers to the mission questions, each tied to its computed evidence.',
          'Separate confirmed findings from suggestive patterns; carry the statistician’s caveats forward.',
          'Recommend concrete next actions and what data would strengthen weak conclusions.',
        ],
        handoff: 'Final insights report',
        handoffContents: 'the complete report with findings, evidence references, caveats, and recommendations',
      },
    ],
  }),


];

module.exports = { ENGINEERING_RECIPES };
